name: module3_task3

on:
  push:
    branches: [master]
    tags:
      - '1.0.0'

  schedule:
    - cron: "0 0 * * *"

jobs:
  tag:
    runs-on: ubuntu-18.04
    steps:
      - name: cloning
        uses: actions/checkout@v2

      - name: set_up
        run: cd module3_task3 && sudo ./setup.sh

      - name: build
        run: cd module3_task3 && make build

      - name: run unit-tests
        run: cd module3_task3 && make unit-tests

      - name: run integration-tests
        run: cd module3_task3 && make integration-tests

      - name: run validate
        run: cd module3_task3 && make validate

      - name: lint
        run: cd module3_task3 && npm install -g markdownlint-cli && make lint

      - name: package
        run: cd module3_task3 && make package

      - name: 1.0.0
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/1.0.0')
        with:
          files: |
            module3_task3/awesome-website.zip
            module3_task3/DEPLOY.md
          body_path: module3_task3/DEPLOY.md
